import { Nav, NavParams, Config } from 'ionic-angular';
import { TodoProvider } from '../../providers/todo-provider';
export declare class TodoListComponent {
    private nav;
    private todoProvider;
    private config;
    private navParams;
    simple: boolean;
    ticket: string;
    user: string;
    LIMIT: number;
    is_empty: boolean;
    is_empty_list: boolean;
    params: any;
    pager: any;
    cachelen: number;
    undone: number;
    cachename: string;
    todoLists: any;
    busy: boolean;
    hidden: boolean;
    initial_load: boolean;
    constructor(nav: Nav, todoProvider: TodoProvider, config: Config, navParams: NavParams);
    ngOnInit(): void;
    getTodos(): void;
    AddTodo(tlist: any): void;
    setDone(todo: any): void;
    setDate(date: any, showmonth?: any, istime?: any): any;
    getFixed(value: any): any;
    itemTapped(tlist: any): void;
}
