export const MOCKS = 
    {
        "tickets/counts": {
            "new_messages": 1,
            "open_all": 284,
            "open_as_tech": 10,
            "open_as_alttech": 2,
            "open_as_user": 1001,
            "onhold": 3,
            "reminder": 0,
            "parts_on_order": 0,
            "unconfirmed": 45,
            "waiting": 2
        },
        "login": {
            "api_token": "re36rym3mjqxm8ej2cscfajmxpsew33m"
        },
        "organizations": [
            {
                "key": "u0diuk",
                "name": "bigWebApps",
                "is_expired": false,
                "is_trial": false,
                "instances": [
                    {
                        "key": "b95s6o",
                        "name": "Support",
                        "is_expired": false,
                        "is_trial": false
                    }
                ]
            },
            {
                "key": "u0diu1",
                "name": "bigWebApps",
                "is_expired": true,
                "is_trial": false,
                "instances": [
                    {
                        "key": "b95s61",
                        "name": "Support1",
                        "is_expired": false,
                        "is_trial": false
                    }
                ]
            },
            {
                "key": "okriez",
                "name": "!testhow",
                "is_expired": false,
                "is_trial": true,
                "instances": [
                    {
                        "key": "byk81d",
                        "name": "Main",
                        "is_expired": false,
                        "is_trial": false
                    },
                    {
                        "key": "byk811",
                        "name": "Second",
                        "is_expired": false,
                        "is_trial": false
                    }
                ]
            }
        ],
        "config": {
            stat: {},
            "key": "2mzer2k5k0srgncebsizvfmip0isp2ii",
            "org": "u0diuk",
            "instance": "b95s6o",
            //"key": "re36rym3mjqxm8ej2cscfajmxpsew33m",
            //"org": "zwoja4",
            //"instance": "ms2asm",
            "is_onhold_status": false,
            "is_time_tracking": true,
            "is_freshbooks": false,
            "freshbooks_url": "https://micajah3.freshbooks.com",
            "is_parts_tracking": false,
            "is_project_tracking": true,
            "is_unassigned_queue": true,
            "is_location_tracking": true,
            "is_waiting_on_response": true,
            "is_invoice": true,
            "is_payments": true,
            "is_expenses": true,
            "is_class_tracking": true,
            "is_travel_costs": true,
            "is_priorities_general": true,
            "is_confirmation_tracking": true,
            "is_resolution_tracking": true,
            "is_ticket_levels": true,
            "is_account_manager": true,
            "is_require_ticket_initial_post": true,
            "is_ticket_require_closure_note": true,
            "is_asset_tracking": true,
            "assets": {
                "unique1_caption": "",
                "unique2_caption": "",
                "unique3_caption": "",
                "unique4_caption": "",
                "unique5_caption": "",
                "unique6_caption": "",
                "unique7_caption": ""
            },
            "timezone_offset": 2,
            "timezone_name": "FLE Standard Time",
            "currency": "$",
            "businessday_length": 540,
            "logo": "/mafsf.axd?d=aW5zdGFuY2UtbG9nby9jOTMzMWE1OWNiNzY0YjQyYmM2M2JhZDRhNTAwZTE4My9zaGVycGFkZXNrXzMxMHg5NS5wbmd8MzAwfDQ1fDB8YzkzMzFhNTljYjc2NGI0MmJjNjNiYWQ0YTUwMGUxODNw0",
            "user": {
                "account_name": "bigWebApps Support",
                "login_id": "51b348ac5ef34ecea7d043f0d2688634",
                "user_id": 1325,
                "email": "jtrue@mail.ru",
                "firstname": "Tech/Admin",
                "lastname": "Eugene",
                "is_techoradmin": true,
                "is_admin": true,
                "is_limit_assigned_tkts": false,
                "is_useworkdaystimer": false,
                "account_id": 0,
                "time_format": 1,
                "date_format": 0
            }
        },
        "classes": [
            {
                "name": "General Inquiry",
                "id": 56,
                "parent_id": 0,
                "hierarchy_level": 0,
                "sub": null,
                "is_lastchild": true,
                "is_restrict_to_techs": false,
                "is_active": true,
                "priority_id": 0,
                "level_override": 0
            },
            {
                "name": "Hardware",
                "id": 106,
                "parent_id": 0,
                "hierarchy_level": 0,
                "sub": [
                    {
                        "name": "Desktop Repair",
                        "id": 109,
                        "parent_id": 106,
                        "hierarchy_level": 1,
                        "sub": [
                            {
                                "name": "MAC Issue",
                                "id": 111,
                                "parent_id": 109,
                                "hierarchy_level": 2,
                                "sub": null,
                                "is_lastchild": true,
                                "is_restrict_to_techs": false,
                                "is_active": true,
                                "priority_id": 0,
                                "level_override": 0
                            },
                            {
                                "name": "PC Issue",
                                "id": 110,
                                "parent_id": 109,
                                "hierarchy_level": 2,
                                "sub": [
                                    {
                                        "name": "sdfasf",
                                        "id": 1111,
                                        "parent_id": 109,
                                        "hierarchy_level": 2,
                                        "sub": null,
                                        "is_lastchild": true,
                                        "is_restrict_to_techs": false,
                                        "is_active": true,
                                        "priority_id": 0,
                                        "level_override": 0
                                    },
                                    {
                                        "name": "sadfasdf",
                                        "id": 1101,
                                        "parent_id": 109,
                                        "hierarchy_level": 2,
                                        "sub": null,
                                        "is_lastchild": true,
                                        "is_restrict_to_techs": false,
                                        "is_active": true,
                                        "priority_id": 0,
                                        "level_override": 0
                                    }
                                ],
                                "is_lastchild": false,
                                "is_restrict_to_techs": false,
                                "is_active": true,
                                "priority_id": 0,
                                "level_override": 0
                            }
                        ],
                        "is_lastchild": false,
                        "is_restrict_to_techs": false,
                        "is_active": true,
                        "priority_id": 0,
                        "level_override": 0
                    }
                ],
                "is_lastchild": false,
                "is_restrict_to_techs": false,
                "is_active": true,
                "priority_id": 0,
                "level_override": 0
            },
            {
                "name": "Mobile",
                "id": 1429,
                "parent_id": 0,
                "hierarchy_level": 0,
                "sub": null,
                "is_lastchild": true,
                "is_restrict_to_techs": true,
                "is_active": true,
                "priority_id": 0,
                "level_override": 0
            },
            {
                "name": "New Updates",
                "id": 60,
                "parent_id": 0,
                "hierarchy_level": 0,
                "sub": null,
                "is_lastchild": true,
                "is_restrict_to_techs": false,
                "is_active": false,
                "priority_id": 0,
                "level_override": 0
            }
        ],
        "technicians" : [
        {
        "id": 7627,
        "email": "u0diuk.b95s6o.abv4m9@app.beta.sherpadesk.com",
        "firstname": "DropBox",
        "lastname": "Email",
        "type": "tech",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 1325,
        "email": "jtrue@mail.ru",
        "firstname": "Tech/Admin",
        "lastname": "Eugene",
        "type": "admin",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 7510,
        "email": "alexey.gavrilov@micajah.com",
        "firstname": "Alexey",
        "lastname": "Gavrilov",
        "type": "admin",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 1,
        "email": "vladimir.gooz@micajah.com",
        "firstname": "Vladimir",
        "lastname": "Gooz",
        "type": "admin",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 7508,
        "email": "vgooz@yahoorenamed.com",
        "firstname": "Vladimir",
        "lastname": "Gooz(Yahoo Renamed)",
        "type": "tech",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 91,
        "email": "michael.khramov@gmail.com",
        "firstname": "Michael",
        "lastname": "Khramov",
        "type": "admin",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 7534,
        "email": "deleted-2014-11-11-mikhail@sherpadesk.com",
        "firstname": "Michael",
        "lastname": "Khranov",
        "type": "admin",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 7511,
        "email": "artem.korzhavin@micajah.com",
        "firstname": "Artem",
        "lastname": "Korzhavin",
        "type": "admin",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 299,
        "email": "deleted-2014-11-11-ben@sherpadesk.com",
        "firstname": "Ben",
        "lastname": "Pfohl",
        "type": "admin",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 8,
        "email": "ben@bigwebapps.com",
        "firstname": "Ben",
        "lastname": "Pfohl",
        "type": "admin",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 11063,
        "email": "deleted-2015-16-4-ben@sherpadesk.com",
        "firstname": "Ben",
        "lastname": "Pfohl",
        "type": "admin",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 6506,
        "email": "michaelproctor@hotmail.com",
        "firstname": "Michael",
        "lastname": "Proctor",
        "type": "tech",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 7596,
        "email": "Sep 17 2014  6:03:44:050PM1212121",
        "firstname": "1212121",
        "lastname": "Queue",
        "type": "queue",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 26,
        "email": "Oct 29 2012  8:44PMFuture Projects",
        "firstname": "Future Projects",
        "lastname": "Queue",
        "type": "queue",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    }
],
        "users" : [
        {
        "id": 7627,
        "email": "u0diuk.b95s6o.abv4m9@app.beta.sherpadesk.com",
        "firstname": "DropBox",
        "lastname": "Email",
        "type": "tech",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 1325,
        "email": "jtrue@mail.ru",
        "firstname": "Tech/Admin",
        "lastname": "Eugene",
        "type": "admin",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 7510,
        "email": "alexey.gavrilov@micajah.com",
        "firstname": "Alexey",
        "lastname": "Gavrilov",
        "type": "admin",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 1,
        "email": "vladimir.gooz@micajah.com",
        "firstname": "Vladimir",
        "lastname": "Gooz",
        "type": "admin",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 7508,
        "email": "vgooz@yahoorenamed.com",
        "firstname": "Vladimir",
        "lastname": "Gooz(Yahoo Renamed)",
        "type": "tech",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 91,
        "email": "michael.khramov@gmail.com",
        "firstname": "Michael",
        "lastname": "Khramov",
        "type": "admin",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 7534,
        "email": "deleted-2014-11-11-mikhail@sherpadesk.com",
        "firstname": "Michael",
        "lastname": "Khranov",
        "type": "admin",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 7511,
        "email": "artem.korzhavin@micajah.com",
        "firstname": "Artem",
        "lastname": "Korzhavin",
        "type": "admin",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 299,
        "email": "deleted-2014-11-11-ben@sherpadesk.com",
        "firstname": "Ben",
        "lastname": "Pfohl",
        "type": "admin",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 8,
        "email": "ben@bigwebapps.com",
        "firstname": "Ben",
        "lastname": "Pfohl",
        "type": "admin",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 11063,
        "email": "deleted-2015-16-4-ben@sherpadesk.com",
        "firstname": "Ben",
        "lastname": "Pfohl",
        "type": "admin",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 6506,
        "email": "michaelproctor@hotmail.com",
        "firstname": "Michael",
        "lastname": "Proctor",
        "type": "tech",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 7596,
        "email": "Sep 17 2014  6:03:44:050PM1212121",
        "firstname": "1212121",
        "lastname": "Queue",
        "type": "queue",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    },
    {
        "id": 26,
        "email": "Oct 29 2012  8:44PMFuture Projects",
        "firstname": "Future Projects",
        "lastname": "Queue",
        "type": "queue",
        "fb_staff_id": 0,
        "qb_employee_id": 0,
        "qb_vendor_id": 0,
        "account_id": null,
        "account_name": null,
        "location_id": null,
        "location_name": null
    }
],
        "projects" : [
        {
        "id": 19,
        "account_id": -1,
        "name": "api.sherpadesk.com",
        "account_name": "bigWebApps Support",
        "open_tickets": 3,
        "closed_tickets": 1,
        "priority": 1,
        "priority_name": "Highest Possible",
        "logged_hours": 266.5000,
        "remaining_hours": 0.0000,
        "complete": 100,
        "client_manager": "Gavrilov, Alexey"
    },
    {
        "id": 9,
        "account_id": -1,
        "name": "New Mobile App  /  Setup Environment",
        "account_name": "bigWebApps Support",
        "open_tickets": 0,
        "closed_tickets": 0,
        "priority": null,
        "priority_name": "",
        "logged_hours": 0.0000,
        "remaining_hours": 0.0000,
        "complete": 0,
        "client_manager": "Clements, Patrick"
    },
    {
        "id": 12,
        "account_id": -1,
        "name": "Test Project Root",
        "account_name": "bigWebApps Support",
        "open_tickets": 1,
        "closed_tickets": 1,
        "priority": null,
        "priority_name": "",
        "logged_hours": 0.0000,
        "remaining_hours": 0.0000,
        "complete": 0,
        "client_manager": ""
    }
],
        "locations" : [
            {
                "id": 13,
                "name": "123I'm testing &amp; &lt;script&gt;alertw(\"!!!\");&"
            },
            {
                "id": 16,
                "name": "Main Office"
            },
            {
                "id": 17,
                "name": "My Office"
            },
            {
                "id": 1272,
                "name": "test"
            },
            {
                "id": 1253,
                "name": "Test location with address"
            }
        ],
        "accounts": [
            {
                "id": -1,
                "name": "SherpaDesk Support",
                "account_statistics": {
                    "ticket_counts": {
                        "open": 133,
                        "closed": 2025,
                        "hours": 27132,
                        "total_invoiced_amount": 0,
                        "total_non_invoiced_amount": 548,
                        "total_billed_amount": 36992,
                        "total_unbilled_amount": 0,
                        "scheduled": 0,
                        "followups": 0
                    },
                    "timelogs": 0,
                    "invoices": 0,
                    "hours": 27132,
                    "expenses": 22
                }
            },
            {
                "id": 574,
                "name": "ACLU",
                "account_statistics": {
                    "ticket_counts": {
                        "open": 1,
                        "closed": 45,
                        "hours": 10,
                        "total_invoiced_amount": 0,
                        "total_non_invoiced_amount": 0,
                        "total_billed_amount": 0,
                        "total_unbilled_amount": 0,
                        "scheduled": 0,
                        "followups": 0
                    },
                    "timelogs": 0,
                    "invoices": 0,
                    "hours": 10,
                    "expenses": 0
                }
            },
            {
                "id": 7744,
                "name": "Aiken County Schools",
                "account_statistics": {
                    "ticket_counts": {
                        "open": 0,
                        "closed": 3,
                        "hours": 6,
                        "total_invoiced_amount": 0,
                        "total_non_invoiced_amount": 0,
                        "total_billed_amount": 0,
                        "total_unbilled_amount": 0,
                        "scheduled": 0,
                        "followups": 0
                    },
                    "timelogs": 0,
                    "invoices": 0,
                    "hours": 6,
                    "expenses": 0
                }
            }
        ],
        "accounts/-1": {
            "id": -1,
            "name": "Riwal",
            "note": "test",
            "is_active": true,
            "is_organization": true,
            "bwd_number": 1013,
            "client_contract_id": 2,
            "number": "123",
            "ref1": "456",
            "ref2": "456",
            "representative_name": "Clements, Patrick",
            "internal_location_name": "testqq",
            "city": "Atlanta",
            "state": "GA",
            "zipcode": "30312",
            "country": "USA",
            "phone1": "404-849-7145",
            "phone2": null,
            "address1": "1 Main St",
            "address2": null,
            "email_suffix": "",
            "fb_client_id": 0,
            "qb_customer_id": 0,
            "logo": "/mafsf.axd?d=aW5zdGFuY2UtbG9nby9mZTdmNTYxN2YwMDk0N2UwODIyMzJiMWIyNDA5YjRlMS9waW1ncHNoX2Z1bGxzaXplX2Rpc3RyLmpwZ3wzMDB8NDV8MHxmZTdmNTYxN2YwMDk0N2UwODIyMzJiMWIyNDA5YjRlMXA1",
            "files": [
                {
                    "id": "accounts-accounts-files/-1/Account Page.png",
                    "name": "Account Page.png",
                    "url": "https://sherpadeskfiles.blob.core.windows.net/fe7f5617f00947e082232b1b2409b4e1/accounts-accounts-files/-1/Account Page.png?sv=2014-02-14&sr=b&sig=PZTmijmZy11w3DBaQXnpXfe%2FzJcn0MPi9rronVonINo%3D&se=2016-03-14T08%3A51%3A36Z&sp=r",
                    "date": "2015-08-31T21:18:02.0000000",
                    "size": 305040
                }
            ],
            "locations": [
                {
                    "id": 2,
                    "name": "Atlanta"
                },
                {
                    "id": 3,
                    "name": "Los Angeles"
                }
            ],
            "users": [
                {
                    "id": 540,
                    "email": "richard.swart@riwal.com",
                    "fullname": "Richard Swart",
                    "phone": "",
                    "type": "user",
                    "is_accounting_contact": false
                },
                {
                    "id": 11099,
                    "email": "nicolas.taillard@riwal.com",
                    "fullname": "Nicolas Taillard",
                    "phone": "",
                    "type": "user",
                    "is_accounting_contact": false
                },
                {
                    "id": 1302,
                    "email": "henk.van.veldhoven@riwal.com",
                    "fullname": "Henk van Veldhoven",
                    "phone": "0031886181827",
                    "type": "user",
                    "is_accounting_contact": false
                }
            ],
            "projects": [
                {
                    "id": 2419,
                    "name": "Account Invite Links",
                    "billing_info": "",
                    "billing_method_id": "",
                    "time_and_billing": "Staff Rate",
                    "open_tickets": 2,
                    "closed_tickets": 0,
                    "logged_hours": 208.2600,
                    "remaining_hours": 0.0000,
                    "complete": 100,
                    "internal_client_manager": ""
                },
                {
                    "id": 2308,
                    "name": "Project and Account UI Redesign",
                    "billing_info": "",
                    "billing_method_id": "",
                    "time_and_billing": "Staff Rate",
                    "open_tickets": 2,
                    "closed_tickets": 1,
                    "logged_hours": 173.5000,
                    "remaining_hours": 0.0000,
                    "complete": 100,
                    "internal_client_manager": ""
                }
            ],
            "assets": [

            ],
            "account_statistics": {
                "ticket_counts": {
                    "open": 17,
                    "closed": 113,
                    "hours": 73.7200,
                    "total_invoiced_amount": 0.0000,
                    "total_non_invoiced_amount": 0.0000,
                    "total_billed_amount": 0.0000,
                    "total_unbilled_amount": 0.0000,
                    "scheduled": 0,
                    "followups": 0
                },
                "timelogs": 3,
                "invoices": 100,
                "hours": 73.7200,
                "expenses": 10.5
            },
            "primary_contact": {
                "fullname": "Swart, Richard",
                "address1": "1 Main St",
                "address2": "",
                "city": "Atlanta",
                "state": "GA",
                "zipcode": "30312",
                "country": "USA",
                "phone1": "404-849-7145",
                "phone2": ""
            },
            "customfields": [

            ]
        },
        "accounts/574": {
            "id": 574,
            "name": "Riwal 11",
            "note": "test hdfh",
            "is_active": true,
            "is_organization": true,
            "bwd_number": 1013,
            "client_contract_id": 2,
            "number": "123",
            "ref1": "456",
            "ref2": "456",
            "representative_name": "Clements, Patrick",
            "internal_location_name": "testqq",
            "city": "Atlanta",
            "state": "GA",
            "zipcode": "30312",
            "country": "USA",
            "phone1": "404-849-7145",
            "phone2": null,
            "address1": "1 Main St",
            "address2": null,
            "email_suffix": "",
            "fb_client_id": 0,
            "qb_customer_id": 0,
            "logo": "/mafsf.axd?d=aW5zdGFuY2UtbG9nby9mZTdmNTYxN2YwMDk0N2UwODIyMzJiMWIyNDA5YjRlMS9waW1ncHNoX2Z1bGxzaXplX2Rpc3RyLmpwZ3wzMDB8NDV8MHxmZTdmNTYxN2YwMDk0N2UwODIyMzJiMWIyNDA5YjRlMXA1",
            "files": [
                {
                    "id": "accounts-accounts-files/-1/Account Page.png",
                    "name": "Account Page.png",
                    "url": "https://sherpadeskfiles.blob.core.windows.net/fe7f5617f00947e082232b1b2409b4e1/accounts-accounts-files/-1/Account Page.png?sv=2014-02-14&sr=b&sig=PZTmijmZy11w3DBaQXnpXfe%2FzJcn0MPi9rronVonINo%3D&se=2016-03-14T08%3A51%3A36Z&sp=r",
                    "date": "2015-08-31T21:18:02.0000000",
                    "size": 305040
                }
            ],
            "locations": [
                {
                    "id": 2,
                    "name": "Atlanta"
                },
                {
                    "id": 3,
                    "name": "Los Angeles"
                }
            ],
            "users": [
                {
                    "id": 540,
                    "email": "richard.swart@riwal.com",
                    "fullname": "Richard Swart",
                    "phone": "",
                    "type": "user",
                    "is_accounting_contact": false
                },
                {
                    "id": 11099,
                    "email": "nicolas.taillard@riwal.com",
                    "fullname": "Nicolas Taillard",
                    "phone": "",
                    "type": "user",
                    "is_accounting_contact": false
                },
                {
                    "id": 1302,
                    "email": "henk.van.veldhoven@riwal.com",
                    "fullname": "Henk van Veldhoven",
                    "phone": "0031886181827",
                    "type": "user",
                    "is_accounting_contact": false
                }
            ],
            "projects": [
            ],
            "assets": [

            ],
            "account_statistics": {
                "ticket_counts": {
                    "open": 17,
                    "closed": 113,
                    "hours": 73.7200,
                    "total_invoiced_amount": 0.0000,
                    "total_non_invoiced_amount": 0.0000,
                    "total_billed_amount": 0.0000,
                    "total_unbilled_amount": 0.0000,
                    "scheduled": 0,
                    "followups": 0
                },
                "timelogs": 3,
                "invoices": 100,
                "hours": 73.7200,
                "expenses": 10.5
            },
            "primary_contact": {
                "fullname": "Swart, Richard",
                "address1": "1 Main St",
                "address2": "",
                "city": "Atlanta",
                "state": "GA",
                "zipcode": "30312",
                "country": "USA",
                "phone1": "404-849-7145",
                "phone2": ""
            },
            "customfields": [

            ]
        },
        "queues": [
            {
                "id": "27",
                "fullname": "Pre-Development",
                "tickets_count": 198
            },
            {
                "id": "271",
                "fullname": "Future Consideration",
                "tickets_count": 76
            },
            {
                "id": "269",
                "fullname": "Website",
                "tickets_count": 2
            },
            {
                "id": "5",
                "fullname": "New Ticket",
                "tickets_count": 1
            },
            {
                "id": "272",
                "fullname": "Mobile App",
                "tickets_count": null
            }
        ],
        "queues/27": [
            {
                "id": 370928,
                "key": "4f5ijv",
                "sla_complete_date": null,
                "created_time": "2015-09-10T01:08:00.0000000",
                "updated_time": "2015-09-28T16:39:00.0000000",
                "closed_time": null,
                "number": 4384,
                "is_new_user_post": false,
                "is_new_tech_post": false,
                "prefix": "",
                "subject": "Logo and Banner Request for Salesforce",
                "support_group_name": "",
                "next_step": "",
                "resolution_category_id": null,
                "resolution_category_name": "",
                "support_group_id": null,
                "initial_post": "Hey Anastasiia!\r\n\r\nWe need a couple of variants of logos and banners for our SalesForce listing.\r\n\r\nHere is what we need.\r\n- High Resolution logo: PNG with a transparent background that is up to 10MB in size\r\n-Banner: a 1200 x 300 pixel PNG that is up to 1MB in size\r\n-Tile Image: a 280x205 pixel PNG file that is up to 300KB in size\r\n\r\nLet me know if you have any questions on this.  Thanks!",
                "user_id": 2,
                "user_firstname": "Patrick",
                "user_lastname": "Clements",
                "user_email": "patrick.clements@bigwebapps.com",
                "tech_id": 119130,
                "technician_firstname": "Anastasiia",
                "technician_lastname": "Chov",
                "technician_email": "nastya_01.88@mail.ru",
                "account_id": -1,
                "account_name": "SherpaDesk Support",
                "location_id": null,
                "location_name": "",
                "account_location_id": null,
                "account_location_name": "",
                "priority_id": 1,
                "priority_name": "General Inquiry",
                "level": 3,
                "level_name": "Active Plate",
                "status": "Open",
                "creation_category_id": null,
                "creation_category_name": "",
                "days_old_in_minutes": 237151,
                "days_old": "164d 16h 31m",
                "class_id": 268,
                "class_name": "SherpaDesk",
                "total_hours": 20.0000
            },
            {
                "id": 147987,
                "key": "sf8c0m",
                "sla_complete_date": "2014-07-15T18:43:00.0000000",
                "created_time": "2014-07-15T18:43:00.0000000",
                "updated_time": "2014-11-25T17:38:00.0000000",
                "closed_time": null,
                "number": 2315,
                "is_new_user_post": true,
                "is_new_tech_post": true,
                "prefix": "",
                "subject": "Email Links to Mobile App",
                "support_group_name": "",
                "next_step": "",
                "resolution_category_id": null,
                "resolution_category_name": "",
                "support_group_id": null,
                "initial_post": "This is my current concept to allow us easier access to the mobile app for testing.   I know this is not great but I don't have a better idea right now.\r\n\r\nI do not love the idea of doing redirects on the web to redirect to mobile or the app.<br><br>Following file was  uploaded: Mobile App Use and Test.png.",
                "user_id": 1,
                "user_firstname": "Jon",
                "user_lastname": "Vickers",
                "user_email": "jon.vickers@micajah.com",
                "tech_id": 1,
                "technician_firstname": "Jon",
                "technician_lastname": "Vickers",
                "technician_email": "jon.vickers@micajah.com",
                "account_id": -1,
                "account_name": "SherpaDesk Support",
                "location_id": 2,
                "location_name": "Atlanta",
                "account_location_id": 2,
                "account_location_name": "Atlanta",
                "priority_id": 3,
                "priority_name": "UI Improvements",
                "level": 3,
                "level_name": "Active Plate",
                "status": "Open",
                "creation_category_id": null,
                "creation_category_name": "",
                "days_old_in_minutes": 843776,
                "days_old": "585d 22h 56m",
                "class_id": 5298,
                "class_name": "SherpaDesk / Email",
                "total_hours": 0.0000
            }
        ],
        "tickets": [
            {
                "id": 370928,
                "key": "4f5ijv",
                "sla_complete_date": null,
                "created_time": "2015-09-10T01:08:00.0000000",
                "updated_time": "2015-09-28T16:39:00.0000000",
                "closed_time": null,
                "number": 4384,
                "is_new_user_post": false,
                "is_new_tech_post": false,
                "prefix": "",
                "subject": "Logo and Banner Request for Salesforce",
                "support_group_name": "",
                "next_step": "",
                "resolution_category_id": null,
                "resolution_category_name": "",
                "support_group_id": null,
                "initial_post": "Hey Anastasiia!\r\n\r\nWe need a couple of variants of logos and banners for our SalesForce listing.\r\n\r\nHere is what we need.\r\n- High Resolution logo: PNG with a transparent background that is up to 10MB in size\r\n-Banner: a 1200 x 300 pixel PNG that is up to 1MB in size\r\n-Tile Image: a 280x205 pixel PNG file that is up to 300KB in size\r\n\r\nLet me know if you have any questions on this.  Thanks!",
                "user_id": 2,
                "user_firstname": "Patrick",
                "user_lastname": "Clements",
                "user_email": "patrick.clements@bigwebapps.com",
                "tech_id": 119130,
                "technician_firstname": "Anastasiia",
                "technician_lastname": "Chov",
                "technician_email": "nastya_01.88@mail.ru",
                "account_id": -1,
                "account_name": "SherpaDesk Support",
                "location_id": null,
                "location_name": "",
                "account_location_id": null,
                "account_location_name": "",
                "priority_id": 1,
                "priority_name": "General Inquiry",
                "level": 3,
                "level_name": "Active Plate",
                "status": "Open",
                "creation_category_id": null,
                "creation_category_name": "",
                "days_old_in_minutes": 237151,
                "days_old": "164d 16h 31m",
                "class_id": 268,
                "class_name": "SherpaDesk",
                "total_hours": 20.0000
            },
            {
                "id": 147987,
                "key": "sf8c0m",
                "sla_complete_date": null,
                "created_time": "2014-07-15T18:43:00.0000000",
                "updated_time": "2014-11-25T17:38:00.0000000",
                "closed_time": null,
                "number": 2315,
                "is_new_user_post": true,
                "is_new_tech_post": true,
                "prefix": "",
                "subject": "Email Links to Mobile App",
                "support_group_name": "",
                "next_step": "",
                "resolution_category_id": null,
                "resolution_category_name": "",
                "support_group_id": null,
                "initial_post": "This is my current concept to allow us easier access to the mobile app for testing.   I know this is not great but I don't have a better idea right now.\r\n\r\nI do not love the idea of doing redirects on the web to redirect to mobile or the app.<br><br>Following file was  uploaded: Mobile App Use and Test.png.",
                "user_id": 1,
                "user_firstname": "Jon",
                "user_lastname": "Vickers",
                "user_email": "jon.vickers@micajah.com",
                "tech_id": 1,
                "technician_firstname": "Jon",
                "technician_lastname": "Vickers",
                "technician_email": "jon.vickers@micajah.com",
                "account_id": -1,
                "account_name": "SherpaDesk Support",
                "location_id": 2,
                "location_name": "Atlanta",
                "account_location_id": 2,
                "account_location_name": "Atlanta",
                "priority_id": 3,
                "priority_name": "UI Improvements",
                "level": 3,
                "level_name": "Active Plate",
                "status": "Open",
                "creation_category_id": null,
                "creation_category_name": "",
                "days_old_in_minutes": 843776,
                "days_old": "585d 22h 56m",
                "class_id": 5298,
                "class_name": "SherpaDesk / Email",
                "total_hours": 2.0000
            }
        ],
        "tickets/4f5ijv": {
            "id": 472187,
            "key": "xa1o2k",
            "created_time": "2016-03-01T17:14:00.0000000",
            "closed_time": "2016-03-02T14:26:00.0000000",
            "request_completion_date": null,
            "is_waiting_on_response": false,
            "waiting_date": null,
            "waiting_minutes": 0,
            "followup_date": null,
            "sla_complete_date": null,
            "sla_response_date": null,
            "confirmed_date": null,
            "next_step_date": null,
            "updated_time": "2016-03-03T16:46:00.0000000",
            "organization_key": "2939b13ac393462b9ae8b9e4d99b521d",
            "department_key": 1,
            "is_deleted": false,
            "user_id": 3,
            "user_title": "",
            "user_firstname": "Mike",
            "user_lastname": "Clements",
            "user_email": "mike.clements@bigwebapps.com",
            "tech_id": 270,
            "tech_firstname": "Eugene",
            "tech_lastname": "Tolmachov",
            "tech_email": "eugene@micajah.com",
            "priority": 4,
            "priority_name": "UI Improvements",
            "priority_id": 3,
            "user_created_id": 270,
            "user_created_firstname": "Eugene",
            "user_created_lastname": "Tolmachov",
            "user_created_email": "eugene@micajah.com",
            "status": "Open",
            "location_id": 3,
            "location_name": "Los Angeles",
            "class_id": 5300,
            "class_name": "SherpaDesk / Mobile",
            "project_id": 0,
            "project_name": "",
            "serial_number": "",
            "folder_id": 0,
            "folder_path": "",
            "creation_category_id": 0,
            "creation_category_name": "",
            "subject": "Mobile App - Access to Notes and Files",
            "note": "",
            "number": 5078,
            "prefix": "",
            "customfields_xml": "<root />",
            "parts_cost": 0.0000,
            "labor_cost": 0.0000,
            "total_time_in_minutes": 600,
            "misc_cost": 10.0000,
            "travel_cost": 0.0000,
            "request_completion_note": "",
            "followup_note": "",
            "initial_response": true,
            "sla_complete_used": 372,
            "sla_response_used": 0,
            "level": 3,
            "level_name": "Active Plate",
            "is_via_email_parser": false,
            "account_id": -1,
            "account_name": "SherpaDesk Support",
            "account_location_id": 3,
            "account_location_name": "Los Angeles",
            "resolution_category_id": 0,
            "resolution_category_name": "",
            "is_resolved": false,
            "confirmed_by_name": "",
            "is_confirmed": false,
            "confirmed_note": "",
            "support_group_id": 0,
            "support_group_name": "",
            "is_handle_by_callcentre": false,
            "submission_category": "",
            "is_user_inactive": false,
            "next_step": "",
            "total_hours": 10.0000,
            "remaining_hours": 0.0000,
            "estimated_time": 0,
            "percentage_complete": 0,
            "workpad": "",
            "scheduled_ticket_id": 0,
            "kb": false,
            "kb_type": 0,
            "kb_publish_level": 0,
            "kb_search_desc": "",
            "kb_alternate_id": "",
            "kb_helpful_count": 0,
            "kb_portal_alias": "Mobile",
            "initial_post": "Eugene,\r\n\r\nWe need to be able to access Notes and Files from the Account Manager section in the mobile.  Is this something you could add fairly easily to the mobile?\r\n\r\nThank you,<br><br>This ticket was entered by Eugene Tolmachov",
            "is_sent_notification_email": true,
            "email_cc": "",
            "related_tickets_count": 0,
            "days_old_in_minutes": 11365,
            "days_old": "7d 21h 25m",
            "tech_type": "Administrator",
            "resolution_categories": [
                {
                    "name": "Duplicate Issue",
                    "id": 15,
                    "is_resolved": false,
                    "is_active": true
                },
                {
                    "name": "End User Submission",
                    "id": 16,
                    "is_resolved": false,
                    "is_active": true
                },
                {
                    "name": "No Longer Valid",
                    "id": 17,
                    "is_resolved": false,
                    "is_active": true
                },
                {
                    "name": "No Response",
                    "id": 18,
                    "is_resolved": false,
                    "is_active": true
                },
                {
                    "name": "Unable to Replicate",
                    "id": 19,
                    "is_resolved": false,
                    "is_active": true
                },
                {
                    "name": "Unable to Resolve",
                    "id": 20,
                    "is_resolved": false,
                    "is_active": true
                }
            ],
            "users": [
                {
                    "user_id": 3,
                    "user_fullname": "Mike Clements",
                    "is_primary": true,
                    "start_date": "2016-03-01T17:14:04.0770000",
                    "stop_date": null
                }
            ],
            "technicians": [
                {
                    "user_id": 270,
                    "user_fullname": "Eugene Tolmachov",
                    "is_primary": true,
                    "start_date": "2016-03-02T16:59:53.6930000",
                    "stop_date": null
                }
            ],
            "ticketlogs": [
                {
                    "id": 1646733,
                    "ticket_key": "xa1o2k",
                    "user_id": 270,
                    "user_email": "eugene@micajah.com",
                    "user_firstname": "Eugene",
                    "user_lastname": "Tolmachov",
                    "record_date": "2016-03-03T16:46:00.0000000",
                    "log_type": "Response",
                    "note": "native updated immediately also, app just show mobile site&lt;br&gt;",
                    "ticket_time_id": 0,
                    "sent_to": "Mike Clements",
                    "is_waiting": false,
                    "sla_used": 0
                },
                {
                    "id": 1646697,
                    "ticket_key": "xa1o2k",
                    "user_id": 3,
                    "user_email": "mike.clements@bigwebapps.com",
                    "user_firstname": "Mike",
                    "user_lastname": "Clements",
                    "record_date": "2016-03-03T16:37:00.0000000",
                    "log_type": "Response",
                    "note": "Pat had added some additional comments as well, breaking out the Files and Nots into their own tab.\r\n\r\nAlso, when we do these updates I know the mobile site m.sherpadesk.com is immediately updated, but what about the native app?\r\n\r\nThanks,\r\n\r\nMike Clements\r\nPhone: 866.996.1200 x 703\r\nmike.clements@bigwebapps.com\r\nbigWebApps",
                    "ticket_time_id": 0,
                    "sent_to": "Eugene Tolmachov",
                    "is_waiting": null,
                    "sla_used": 0
                },
                {
                    "id": 1645254,
                    "ticket_key": "xa1o2k",
                    "user_id": 270,
                    "user_email": "eugene@micajah.com",
                    "user_firstname": "Eugene",
                    "user_lastname": "Tolmachov",
                    "record_date": "2016-03-03T11:10:00.0000000",
                    "log_type": "Response",
                    "note": "yea, this is good,&lt;br&gt;ill do it",
                    "ticket_time_id": 0,
                    "sent_to": "Mike Clements",
                    "is_waiting": false,
                    "sla_used": 0
                },
                {
                    "id": 1643104,
                    "ticket_key": "xa1o2k",
                    "user_id": 3,
                    "user_email": "mike.clements@bigwebapps.com",
                    "user_firstname": "Mike",
                    "user_lastname": "Clements",
                    "record_date": "2016-03-02T17:00:00.0000000",
                    "log_type": "ReOpened",
                    "note": "Ticket was ReOpened by Mike Clements.",
                    "ticket_time_id": 0,
                    "sent_to": "",
                    "is_waiting": null,
                    "sla_used": 0
                },
                {
                    "id": 1643098,
                    "ticket_key": "xa1o2k",
                    "user_id": 3,
                    "user_email": "mike.clements@bigwebapps.com",
                    "user_firstname": "Mike",
                    "user_lastname": "Clements",
                    "record_date": "2016-03-02T16:59:00.0000000",
                    "log_type": "Response",
                    "note": "Eugene,\r\n\r\nThis looks pretty good.  Is there any way to fix the spacing on the notes?\r\n\r\nHere’s what it looks like on the web\r\n[cid:4078BF5AC2C94B6FBAA6FE3E4A74668A]\r\n\r\nHowever if you look at it on the mobile theres some weird spacing\r\n\r\n[cid:94881AE156B04D518CCF86474FD506BB]\r\nMike Clements\r\nPhone: 866.996.1200 x 703\r\nmike.clements@bigwebapps.com\r\nbigWebApps\r\n\r\nFollowing files were uploaded: 4078BF5A-C2C9-4B6F-BAA6-FE3E4A74668A.png, 94881AE1-56B0-4D51-8CCF-86474FD506BB.png",
                    "ticket_time_id": 0,
                    "sent_to": "Eugene Tolmachov",
                    "is_waiting": null,
                    "sla_used": 0
                },
                {
                    "id": 1642226,
                    "ticket_key": "xa1o2k",
                    "user_id": 270,
                    "user_email": "eugene@micajah.com",
                    "user_firstname": "Eugene",
                    "user_lastname": "Tolmachov",
                    "record_date": "2016-03-02T14:27:00.0000000",
                    "log_type": "Response",
                    "note": "[cid:Copy9a97982650c5zip]",
                    "ticket_time_id": 0,
                    "sent_to": "Mike Clements",
                    "is_waiting": false,
                    "sla_used": 0
                },
                {
                    "id": 1642224,
                    "ticket_key": "xa1o2k",
                    "user_id": 270,
                    "user_email": "eugene@micajah.com",
                    "user_firstname": "Eugene",
                    "user_lastname": "Tolmachov",
                    "record_date": "2016-03-02T14:26:00.0000000",
                    "log_type": "Closed",
                    "note": "done<br><br>Ticket was CLOSED by Eugene Tolmachov.<br>Eugene Tolmachov logged 10.00 hours (10 hours) as Software Dev task type.",
                    "ticket_time_id": 0,
                    "sent_to": "",
                    "is_waiting": null,
                    "sla_used": 0
                },
                {
                    "id": 1639415,
                    "ticket_key": "xa1o2k",
                    "user_id": 3,
                    "user_email": "mike.clements@bigwebapps.com",
                    "user_firstname": "Mike",
                    "user_lastname": "Clements",
                    "record_date": "2016-03-01T17:14:00.0000000",
                    "log_type": "Initial Post",
                    "note": "Eugene,\r\n\r\nWe need to be able to access Notes and Files from the Account Manager section in the mobile.  Is this something you could add fairly easily to the mobile?\r\n\r\nThank you,<br><br>This ticket was entered by Eugene Tolmachov",
                    "ticket_time_id": 0,
                    "sent_to": "",
                    "is_waiting": null,
                    "sla_used": 0
                }
            ],
            "assets": [

            ],
            "attachments": [
                {
                    "id": "tickets-tickets-files/472187/Copy9a97982650c5.zip",
                    "name": "Copy9a97982650c5.zip",
                    "url": "https://sherpadeskfiles.blob.core.windows.net/fe7f5617f00947e082232b1b2409b4e1p/tickets-tickets-files/472187/Copy9a97982650c5.zip",
                    "date": "2016-03-02T14:26:36.0000000",
                    "size": 74099
                },
                {
                    "id": "tickets-tickets-files/472187/4078BF5A-C2C9-4B6F-BAA6-FE3E4A74668A.png",
                    "name": "4078BF5A-C2C9-4B6F-BAA6-FE3E4A74668A.png",
                    "url": "https://sherpadeskfiles.blob.core.windows.net/fe7f5617f00947e082232b1b2409b4e1p/tickets-tickets-files/472187/4078BF5A-C2C9-4B6F-BAA6-FE3E4A74668A.png",
                    "date": "2016-03-02T16:59:22.0000000",
                    "size": 71798
                },
                {
                    "id": "tickets-tickets-files/472187/94881AE1-56B0-4D51-8CCF-86474FD506BB.png",
                    "name": "94881AE1-56B0-4D51-8CCF-86474FD506BB.png",
                    "url": "https://sherpadeskfiles.blob.core.windows.net/fe7f5617f00947e082232b1b2409b4e1p/tickets-tickets-files/472187/94881AE1-56B0-4D51-8CCF-86474FD506BB.png",
                    "date": "2016-03-02T16:59:22.0000000",
                    "size": 121846
                }
            ],
            "classes": [
                {
                    "name": "SherpaDesk",
                    "id": 268,
                    "parent_id": 0,
                    "hierarchy_level": 0,
                    "sub": null,
                    "is_lastchild": false,
                    "is_restrict_to_techs": false,
                    "is_active": true,
                    "priority_id": 0,
                    "level_override": 0
                },
                {
                    "name": "Mobile",
                    "id": 5300,
                    "parent_id": 268,
                    "hierarchy_level": 1,
                    "sub": null,
                    "is_lastchild": true,
                    "is_restrict_to_techs": true,
                    "is_active": true,
                    "priority_id": 0,
                    "level_override": 0
                }
            ],
            "BillRate": 0,
            "WaitingUsedBeforeReopen": 0
        }, 
        "time" : [
        {
        "time_id": 39973,
        "project_name": "",
        "user_name": "Vladimir Gooz",
        "user_email": "vladimir.gooz@micajah.com",
        "user_id": 6,
        "note": "Testing and bug fixing before production deploment. Check error tracker on new bugs.",
        "date": "2016-03-11T16:49:00.0000000",
        "stop_time": "2016-03-11T16:49:00.0000000",
        "start_time": "2016-03-11T16:49:00.0000000",
        "hours": 4.0000,
        "fb_id": 0,
        "is_project_log": true,
        "ticket_id": 111,
        "task_type_id": 56,
        "task_type": "Software Dev",
        "project_id": 10,
        "account_id": -1,
        "ticket_number": 0,
        "account_name": "SherpaDesk Support",
        "ticket_subject": "",
        "invoice_id": 0,
        "billable": false,
        "invoice_pseudo_id": "",
        "qb_id": 0,
        "payment_id": 0,
        "contract_name": ""
    },
    {
        "time_id": 262415,
        "project_name": "",
        "user_name": "Igor Vladyka",
        "user_email": "igor.vladyka@micajah.com",
        "user_id": 57,
        "note": "sdgkljklagj dfgjldkjg   Bug in Time tab Bug in Time tab",
        "date": "2016-03-11T14:50:00.0000000",
        "stop_time": "2016-03-11T16:49:00.0000000",
        "start_time": "2016-03-11T16:49:00.0000000",
        "hours": 6.7600,
        "fb_id": 0,
        "is_project_log": false,
        "ticket_id": 464699,
        "task_type_id": 56,
        "task_type": "Software Dev",
        "project_id": 10,
        "account_id": -1,
        "ticket_number": 5036,
        "account_name": "SherpaDesk Support",
        "ticket_subject": "Avatar/Gravitar Bug in Time tab Bug in Time tab Bug in Time tab Bug in Time tab",
        "invoice_id": 10,
        "billable": true,
        "invoice_pseudo_id": "      ",
        "qb_id": 0,
        "payment_id": 0,
        "contract_name": "gdfg"
    },
    {
        "time_id": 262905,
        "project_name": "",
        "user_name": "Yura Yuriev",
        "user_email": "yura.yuriev@micajah.com",
        "user_id": 97,
        "note": "",
        "date": "2016-03-11T13:50:00.0000000",
        "stop_time": null,
        "start_time": null,
        "hours": 8.0000,
        "fb_id": 0,
        "is_project_log": false,
        "ticket_id": 470798,
        "task_type_id": 56,
        "task_type": "Software Dev",
        "project_id": 0,
        "account_id": -1,
        "ticket_number": 5071,
        "account_name": "SherpaDesk Support",
        "ticket_subject": "Azure Search Upgrades",
        "invoice_id": 0,
        "billable": true,
        "invoice_pseudo_id": "      ",
        "qb_id": 0,
        "payment_id": 0,
        "contract_name": ""
    },
    {
        "time_id": 262014,
        "project_name": "",
        "user_name": "Igor Vladyka",
        "user_email": "igor.vladyka@micajah.com",
        "user_id": 57,
        "note": "",
        "date": "2016-03-10T15:44:00.0000000",
        "stop_time": null,
        "start_time": null,
        "hours": 9.1500,
        "fb_id": 0,
        "is_project_log": false,
        "ticket_id": 475888,
        "task_type_id": 56,
        "task_type": "Software Dev",
        "project_id": 0,
        "account_id": -1,
        "ticket_number": 5116,
        "account_name": "SherpaDesk Support",
        "ticket_subject": "Permissions on Inviting Org and User",
        "invoice_id": 0,
        "billable": true,
        "invoice_pseudo_id": "      ",
        "qb_id": 0,
        "payment_id": 0,
        "contract_name": ""
    },
    {
        "time_id": 39857,
        "project_name": "",
        "user_name": "Igor Vladyka",
        "user_email": "igor.vladyka@micajah.com",
        "user_id": 57,
        "note": "Conversation with Yura Yuriev",
        "date": "2016-03-10T14:41:00.0000000",
        "stop_time": null,
        "start_time": null,
        "hours": 0.1700,
        "fb_id": 0,
        "is_project_log": true,
        "ticket_id": 0,
        "task_type_id": 56,
        "task_type": "Software Dev",
        "project_id": 0,
        "account_id": -1,
        "ticket_number": 0,
        "account_name": "SherpaDesk Support",
        "ticket_subject": "",
        "invoice_id": 0,
        "billable": true,
        "invoice_pseudo_id": "      ",
        "qb_id": 0,
        "payment_id": 0,
        "contract_name": ""
    }
],
        "invoices" : [
            {
                "id": 1695,
                "key": "ihpw7d",
                "project_id": -1,
                "account_id": 3126,
                "customer": "Allsups",
                "date": "2016-02-08T22:06:00.0000000",
                "start_date": "2015-03-10T07:27:00.0000000",
                "end_date": "2015-03-13T15:05:00.0000000",
                "timelogs_count": 4,
                "total_hours": 12.8300,
                "amount": 256.6000,
                "travel_cost": 0.0000,
                "misc_cost": 0.0000,
                "total_cost": 256.6000,
                "adjustments": 0,
                "adjustments_note": null,
                "is_fb_exported": false,
                "is_qb_exported": false,
                "is_no_rate_plan": null,
                "account_name": "Allsups",
                "project_name": "",
                "qb_invoice_id": 0,
                "qb_customer_id": 330,
                "recipients": [
                    {
                        "id": 18961,
                        "email": "nick.holmes@allsups.com",
                        "fullname": "Nick Holmes",
                        "phone": "",
                        "type": "user",
                        "is_accounting_contact": true
                    },
                    {
                        "id": 88490,
                        "email": "larry.lewis@allsups.com",
                        "fullname": "Larry Lewis",
                        "phone": "",
                        "type": "user",
                        "is_accounting_contact": true
                    },
                    {
                        "id": 14599,
                        "email": "chris.mccarty@allsups.com",
                        "fullname": "Chris McCarty",
                        "phone": "",
                        "type": "user",
                        "is_accounting_contact": true
                    },
                    {
                        "id": 79483,
                        "email": "linda.wilhite@allsups.com",
                        "fullname": "Linda Wilhite",
                        "phone": "",
                        "type": "user",
                        "is_accounting_contact": true
                    }
                ],
                "time_logs": null,
                "travel_logs": null,
                "expenses": null,
                "retainers": null
            },
            {
                "id": 1693,
                "key": "ihpe7d",
                "project_id": -1,
                "account_id": 3126,
                "customer": "Allsups",
                "date": "2016-02-08T22:06:00.0000000",
                "start_date": "2015-03-10T07:27:00.0000000",
                "end_date": "2015-03-13T15:05:00.0000000",
                "timelogs_count": 5,
                "total_hours": 121.8300,
                "amount": 26.6000,
                "travel_cost": 10.0000,
                "misc_cost": 30.0000,
                "total_cost": 256.6000,
                "adjustments": 40,
                "adjustments_note": "ewfger",
                "is_fb_exported": false,
                "is_qb_exported": false,
                "is_no_rate_plan": null,
                "account_name": "Allsups",
                "project_name": "ergter",
                "qb_invoice_id": 0,
                "qb_customer_id": 330,
                "recipients": [
                    {
                        "id": 18961,
                        "email": "nick.holmes@allsups.com",
                        "fullname": "Nick Holmes",
                        "phone": "",
                        "type": "user",
                        "is_accounting_contact": true
                    },
                    {
                        "id": 88490,
                        "email": "larry.lewis@allsups.com",
                        "fullname": "Larry Lewis",
                        "phone": "",
                        "type": "user",
                        "is_accounting_contact": true
                    },
                    {
                        "id": 14599,
                        "email": "chris.mccarty@allsups.com",
                        "fullname": "Chris McCarty",
                        "phone": "454",
                        "type": "user",
                        "is_accounting_contact": true
                    },
                    {
                        "id": 79483,
                        "email": "linda.wilhite@allsups.com",
                        "fullname": "Linda Wilhite",
                        "phone": "",
                        "type": "user",
                        "is_accounting_contact": true
                    }
                ],
                "time_logs": null,
                "travel_logs": null,
                "expenses": null,
                "retainers": null
            }
        ]
    };